[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  # Izinkan Next.js server functions berjalan di Netlify Edge/Node
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/next_api_auth/:splat"
  status = 200
